### ISSUE TITLE
PHP output get's confused with `r>`, `d>` and `=>`

### ISSUE THREAD

**Issue by CRHain88** [dwightjack/grunt-premailer#22]
Any `r>`, `d>` or `=>` inside PHP tags will output to `?>`.

**Comment by minijus** [comment]
@CRHain88 Did you manage to solve this issue? I found out the same problem recently. I did a bit of research and released that this is not caused by grunt-premailer but by premailer itself (tested it in CLI). To be more specific, '=>' is changed to '?>'  when premailer is using hpricot. And switching to nokogiri instead does not solve the problem since '>' then becomes '&gt;' and '=>' sometimes '=?>'

**Comment by amclin** [comment]
In my experience, you're best running premailer against the final output, instead of PHP or other language templates.

**Comment by minijus** [comment]
@amclin would you suggest first prefilling all personal information like name, registration confirmation link and only then parse it with premailer?

**Comment by amclin** [comment]
If it's for batch processing, I wouldn't run on every recipient. Instead I'd run premailer on my markup with dummy content, and convert the output of that into PHP templates.

**Comment by dwightjack** [comment]
Hi,

sadly I'm not that much into Ruby to be able to look at it. I guess you'll have better luck opening an issue in the premailer repo.

Anyway I also suggest to run premailer against a template and then make it _dynamic_ by addind PHP tags.
